version: '3'
services:
  nginx:
    restart: always #this is what controls the trafic so we need this up all the time
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - api
      - client
  postgres:
    image: 'postgres:latest'
    environment: #need to specify this postgres
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  api: #changed from server to api to avoid conflicts with nginx 
    build: 
      dockerfile: Dockerfile.dev #we only specify the name here
      context: ./api # this is where we specify the location and what files to use for building the image
    volumes:
      - /app/node_modules
      - ./api:/app
    environment: #this is an array of values
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment: #to fix "Calculated Nothing Yet" error 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
