version: '3'
services:
    #don't have redis or postgres here (using aws services)
    api: 
      image: "augmart/multi-api"
      hostname: api #defines a custom host name for the container
      environment: 
        - REDIS_HOST=$REDIS_HOST #elastic beanstalk environment variables
        - REDIS_PORT=$REDIS_PORT
        - PGUSER=$PGUSER
        - PGHOST=$PGHOST
        - PGDATABASE=$PGDATABASE
        - PGPASSWORD=$PGPASSWORD
        - PGPORT=$PGPORT
    client: 
      image: "augmart/multi-client"
      hostname: client 
    worker:  
      image: "augmart/multi-worker"
      hostname: worker
      environment:
        - REDIS_HOST=$REDIS_HOST
        - REDIS_PORT=$REDIS_PORT
    nginx:  
      image: "augmart/multi-nginx"
      hostname: nginx 
      ports: 
        - "80:80"
      depends_on: 
        - api 
        - client 
